FROM envoyproxy/envoy:v1.19.1

COPY envoy.yaml /etc/envoy/envoy.yaml

# RUN apt-get update && apt-get -q install -y \
#     curl
# CMD /usr/local/bin/envoy -c /etc/front-envoy.yaml --service-cluster front-proxy
